### ISSUE TITLE
How do you download on windows?

### ISSUE THREAD

**Issue by signata** [jareer12/RoCAT#2]
command-line-arguments
.\main.go:34:2: undefined: initFiles
.\main.go:35:2: undefined: initDirs
.\main.go:40:20: undefined: New
.\main.go:45:18: undefined: New
.\main.go:71:20: undefined: getUserInfo
.\main.go:112:25: undefined: getCatalogue
.\main.go:117:27: undefined: getClothing
.\main.go:117:39: undefined: GetClothesRequest
.\main.go:135:33: undefined: getTemplateId
.\main.go:140:23: undefined: downloadTemplate
.\main.go:140:23: too many errors

How to fix this? when I do go run main.go it says that

**Comment by Thecoderofthecenturythegoats** [comment]
try harder that is whaat i did and it worked

**Comment by jareer12** [comment]
> command-line-arguments .\main.go:34:2: undefined: initFiles .\main.go:35:2: undefined: initDirs .\main.go:40:20: undefined: New .\main.go:45:18: undefined: New .\main.go:71:20: undefined: getUserInfo .\main.go:112:25: undefined: getCatalogue .\main.go:117:27: undefined: getClothing .\main.go:117:39: undefined: GetClothesRequest .\main.go:135:33: undefined: getTemplateId .\main.go:140:23: undefined: downloadTemplate .\main.go:140:23: too many errors
> 
> How to fix this? when I do go run main.go it says that

try running `go mod tidy`

**Comment by jareer12** [comment]
Run `go run ./` instead of `go run main.go`

**Comment by jareer12** [comment]
https://github.com/jareer12/RoCAT/releases/tag/stable
