### ISSUE TITLE
Undefined: <variable> Error when running "go run main.go" command.

### ISSUE THREAD

**Issue by pashkatate** [jareer12/RoCAT#4]
# command-line-arguments
.\main.go:36:2: undefined: initFiles
.\main.go:37:2: undefined: initDirs
.\main.go:42:20: undefined: New
.\main.go:47:18: undefined: New
.\main.go:73:20: undefined: getUserInfo
.\main.go:114:25: undefined: getCatalogue
.\main.go:119:27: undefined: getClothing
.\main.go:119:39: undefined: GetClothesRequest
.\main.go:137:33: undefined: getTemplateId
.\main.go:142:23: undefined: downloadTemplate
.\main.go:142:23: too many errors

**Comment by jareer12** [comment]
Run `go run ./` or `go build`
